# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchstep < Formula
  desc "YAML-first workflow orchestration engine"
  homepage "https://orchstep.dev"
  version "0.11.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orchstep/orchstep/releases/download/v0.11.0/orchstep_0.11.0_darwin_amd64.tar.gz"
      sha256 "9d556751ee4a246b2b6710998fc9efb7548dd5f6c9e21d0237a994c9bf5d613c"

      define_method(:install) do
        bin.install "orchstep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orchstep/orchstep/releases/download/v0.11.0/orchstep_0.11.0_darwin_arm64.tar.gz"
      sha256 "5cecff77957849f00c865ebc586155ed6f135f5b7203108b8cda04a4bafe9c31"

      define_method(:install) do
        bin.install "orchstep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchstep/orchstep/releases/download/v0.11.0/orchstep_0.11.0_linux_amd64.tar.gz"
      sha256 "241dde88606efc29100eb19a6d57b7aa5a44838d3b40071e7489f62ba01694aa"
      define_method(:install) do
        bin.install "orchstep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orchstep/orchstep/releases/download/v0.11.0/orchstep_0.11.0_linux_arm64.tar.gz"
      sha256 "175cda23a84c2dc19cab98cec115efcbdef23ded5bacbf90c3b019d92e0fb3d0"
      define_method(:install) do
        bin.install "orchstep"
      end
    end
  end

  test do
    system "#{bin}/orchstep", "version"
  end
end
